Fix a bug when using GET instead of POST
TypeError: Cannot read property 'oauth_token' of undefined

The lookup function is a copy & paste from:
https://github.com/jaredhanson/passport-local/blob/master/lib/passport-local/strategy.js